pool:
  vmImage: ubuntu-latest
 
- task: SynopsysSecurityScan@1
  inputs:
    scanType: 'blackduck'
    bridge_blackduck_url: 'https://testing.blackduck.synopsys.com'
    bridge_blackduck_token: 'MGI5ODA0NzktZGI5Ni00OWEyLWE2ZjgtZGYwYThlZjI0NTA0OmU5ZGJhZTc2LTI5MWItNGUwMi1iOTU3LWYwZWQ4MzFmNmZlOA=='
    bridge_blackduck_scan_full: true




  



